# Numpy

**Covered Topics**
- Introduction
- Accessing
- Arithmatic
- Summations

In [ ]:
pip install numpy

In [ ]:
import numpy

In [ ]:
import numpy as np

## Creating Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 0 Dimension

arr = np.array(42)

print(arr)

42


In [ ]:
# 1 Dimension

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
# 2 Dimension

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 Dimension

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# Check Dimension

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# High Dimension

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Accessing

### 1d Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


### 2d Array

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


### 3D array

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) #siku pertama, siku kedua, kolom

6


## Negative Indexing

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


## Arithmatic

In [ ]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 200  420  660  920 1200 1500]


In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
             0]


In [ ]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array([2,4,6,8,10])
print(arr1)
print(arr2)

[1 3 5 7 9]
[ 2  4  6  8 10]


In [ ]:
add = np.add(arr1,arr2) #tambah atas bawah (max 3 array)
add #ketika ditambah ukurannya harus sama

array([ 3,  7, 11, 15, 19])

In [ ]:
subtract = np.subtract(arr1,arr2)
subtract

array([-1, -1, -1, -1, -1])

In [ ]:
np.abs(subtract)

array([1, 1, 1, 1, 1])

In [ ]:
multiply = np.multiply(arr1, arr2)
multiply

array([ 2, 12, 30, 56, 90])

In [ ]:
division = np.divide(arr1, arr2)
division

array([0.5       , 0.75      , 0.83333333, 0.875     , 0.9       ])

In [ ]:
np.round(division)

array([0., 1., 1., 1., 1.])

In [ ]:
np.ceil(division)

array([1., 1., 1., 1., 1.])

In [ ]:
np.floor(division)

array([0., 0., 0., 0., 0.])

In [ ]:
power = np.power(arr1,arr2)
power

array([         1,         81,      15625,    5764801, 3486784401])

## Summations

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


In [ ]:
import numpy as np

arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


In [ ]:
print(arr1)
print(arr2)

[1 3 5 7 9]
[ 2  4  6  8 10]


In [ ]:
sum = np.sum([arr1,arr2,arr1,arr2,arr1,arr2])
sum

165

In [ ]:
sum_axis = np.sum([arr1,arr2,arr1,arr2,arr1,arr2,arr1,arr2], axis = 1)
sum_axis

array([25, 30, 25, 30, 25, 30, 25, 30])

In [ ]:
diff = np.diff([arr1,arr2], axis = 1)
diff

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

#Additional

In [ ]:
umur = np.array([13,52,32,65,34,22,23,21])
umur

array([13, 52, 32, 65, 34, 22, 23, 21])

In [ ]:
np.mean(umur)

32.75

In [ ]:
np.median(umur)

27.5

In [ ]:
np.std(umur)

16.399314010043224

In [ ]:
np.max(umur)

65

In [ ]:
np.min(umur)

13

# Python Pandas

**Covered Topics**
- Initialization
- Column selection, addition, deletion
- Data Indexing & Selecting
- Handling Missing Value
- Combining Datasets
- Grouping and Sorting
- Pivot table
- Working with string
- Working with time series


### Initialization

### Import Library Pandas
Untuk dapat menginstall pandas, kamu bisa menjalankan perintah dengan menggunakan pip


```
pip install pandas
```



In [ ]:
# pip install pandas

Jika sudah berhasil melakukan instalasi Pandas, kita dapat menggunakannya dengan cara import modul tersebut.


```
import pandas as pd
import numpy as np
```



In [ ]:
import pandas as pd
import numpy as np

## Creating Dataframe
DataFrame adalah struktur data tabular yang disusun pada kolom dan baris berurut. Dataframe layaknya seperti 2-dimensi array, You can think of a data frame is like a table.

<img src="https://www.w3resource.com/w3r_images/pandas-data-structure.svg">

Create dataframe using dictionary

In [ ]:
data_penjualan = {
  "product": ["product A", "product B", "product C", "product X"],
  "hasil_penjualan": [500000, 700000, 125000, 350000]
}

In [ ]:
data_penjualan

{'product': ['product A', 'product B', 'product C', 'product X'],
 'hasil_penjualan': [500000, 700000, 125000, 350000]}

In [ ]:
#load data into a DataFrame object:
df = pd.DataFrame(data_penjualan)

print(df)

     product  hasil_penjualan
0  product A           500000
1  product B           700000
2  product C           125000
3  product X           350000


In [ ]:
df

product  hasil_penjualan
0  product A           500000
1  product B           700000
2  product C           125000
3  product X           350000

## Reading or loading the data from file

Untuk membaca data dari file berupa csv kita dapat melakukannya dengan command:

```
pd.read_csv
```



In [ ]:
# download file from https://data.jakarta.go.id/dataset/data-penumpang-bus-sekolah-kpi
# penumpang-bus-sekolah-januari-2017.csv
df = pd.read_csv('Data_Penumpang Bus Sekolah Tahun 2021.csv')
df.head()

periode_data                type_operasi    area_operasi  jumlah_bus  \
0        202101         Puskesmas Cilincing  RS Wisma Atlet         1.0   
1        202101             Puskesmas Tebet  RS Wisma Atlet         1.0   
2        202101     Puskesmas Cempaka Putih  RS Wisma Atlet         1.0   
3        202101     Puskesmas Tanjung Priok  RS Wisma Atlet         1.0   
4        202101  Puskesmas Ciracas Tahap II  RS Wisma Atlet         1.0   

   jumlah_penumpang  
0               8.0  
1              24.0  
2              14.0  
3              10.0  
4               9.0

## cek sample data

`df.head()` dapat digunakan untuk melihat sample data row paling atas

In [ ]:
df.head()

periode_data                type_operasi    area_operasi  jumlah_bus  \
0        202101         Puskesmas Cilincing  RS Wisma Atlet         1.0   
1        202101             Puskesmas Tebet  RS Wisma Atlet         1.0   
2        202101     Puskesmas Cempaka Putih  RS Wisma Atlet         1.0   
3        202101     Puskesmas Tanjung Priok  RS Wisma Atlet         1.0   
4        202101  Puskesmas Ciracas Tahap II  RS Wisma Atlet         1.0   

   jumlah_penumpang  
0               8.0  
1              24.0  
2              14.0  
3              10.0  
4               9.0

In [ ]:
df.head(10)

periode_data                type_operasi    area_operasi  jumlah_bus  \
0        202101         Puskesmas Cilincing  RS Wisma Atlet         1.0   
1        202101             Puskesmas Tebet  RS Wisma Atlet         1.0   
2        202101     Puskesmas Cempaka Putih  RS Wisma Atlet         1.0   
3        202101     Puskesmas Tanjung Priok  RS Wisma Atlet         1.0   
4        202101  Puskesmas Ciracas Tahap II  RS Wisma Atlet         1.0   
5        202101         Puskesmas Jagakarsa  RS Wisma Atlet         1.0   
6        202101         Puskesmas Jagakarsa  RS Wisma Atlet         1.0   
7        202101       Puskesmas Duren Sawit  RS Wisma Atlet         1.0   
8        202101   Puskesmas Ciracas Tahap I  RS Wisma Atlet         1.0   
9        202101         Puskesmas Cilincing  RS Wisma Atlet         1.0   

   jumlah_penumpang  
0               8.0  
1              24.0  
2              14.0  
3              10.0  
4               9.0  
5               5.0  
6              10.0  
7               7.0  
8              22.0  
9              14.0

Untuk menampilkan n record terakhir, dapat menggunakan perintah `tail(n)`. Jika tidak diberi parameter jumlah recordnya, maka secara default akan menampilkan 5 record

In [ ]:
df.tail(10)

periode_data  type_operasi  \
2650        202108  RUTE REGULER   
2651        202108  RUTE REGULER   
2652        202108  RUTE REGULER   
2653        202108  RUTE REGULER   
2654        202108  RUTE REGULER   
2655        202108  RUTE REGULER   
2656        202108  RUTE REGULER   
2657        202108  RUTE REGULER   
2658        202108  RUTE REGULER   
2659        202108  RUTE REGULER   

                                           area_operasi  jumlah_bus  \
2650          RUTE 8 (PS.MINGGU - PANCORAN - MANGGARAI)         5.0   
2651      RUTE 9 (CILINCING - PLUMPANG - P.KEMERDEKAAN)         6.0   
2652                  RUTE 10 (KP.MELAYU - LAP.BANTENG)        10.0   
2653                         RUTE 11 (BLOK M - CILEDUG)        26.0   
2654          RUTE 12 (TERMINAL KALIDERES - GAJAH MADA)        10.0   
2655  RUTE 13 (PULOGADUNG - PD.BAMBU - KALI MALANG -...         2.0   
2656                         RUTE 14 (BLOK M - PD.LABU)         3.0   
2657         RUTE 15 (TEBET - CIPINANG MUARA - PD.KOPI)         0.0   
2658          RUTE 16 (RUSUN MUARA BARU PLUIT - GROGOL)         0.0   
2659  RUTE 17 (RUSUN MUARA BARU PLUIT - BANDENGAN MU...         0.0   

      jumlah_penumpang  
2650               2.0  
2651               2.0  
2652               2.0  
2653               2.0  
2654               2.0  
2655               2.0  
2656               2.0  
2657               2.0  
2658               2.0  
2659               2.0

Fungsi `sample()` pada Pandas dapat digunakan jika kita ingin menampilkan dataframe secara acak. Misalkan menampilkan 10 dataframe secara acak

In [ ]:
df.sample(10)

periode_data                       type_operasi       area_operasi  \
1559        202105                 Puskesmas Cipayung     RS Wisma Atlet   
1350        202106                Puskesmas Cilincing     RS Wisma Atlet   
1230        202106                Puskesmas Kemayoran     RS Wisma Atlet   
410         202102        Puskesmas Rawabadak Selatan     RS Wisma Atlet   
2408        202107                Puskesmas Kemayoran     RS Wisma Atlet   
1613        202106                 Puskesmas Cilandak     RS Wisma Atlet   
1212        202106            Puskesmas Cempaka Putih     RS Wisma Atlet   
720         202102                       RSUD CIRACAS            JAKARTA   
320         202102                  Puskesmas Makasar     RS Wisma Atlet   
2582        202108  RS Wisma Atlet (Vaksinator Nakes)  GROGOL PETAMBURAN   

      jumlah_bus  jumlah_penumpang  
1559         1.0              12.0  
1350         1.0              20.0  
1230         1.0              19.0  
410          1.0              35.0  
2408         1.0              20.0  
1613         1.0               6.0  
1212         1.0               8.0  
720          NaN               NaN  
320          1.0              19.0  
2582         0.0               0.0

## Informasi Struktur Data

Property shape dapat digunakan untuk mengetahui dimensi dari dataframe

In [ ]:
df.shape

(2660, 5)

Dari nilai property shape yang terlihat diatas, memberikan informasi bahwa DataFrame memiliki 31 baris/record dan 5 kolom.





Property DataFrame lainnya adalah `dtypes`, yang dapat digunakan untuk melihat struktur dari data

`df.dtypes`

In [ ]:
df.dtypes

periode_data          int64
type_operasi         object
area_operasi         object
jumlah_bus          float64
jumlah_penumpang    float64
dtype: object

Informasi lebih detail mengenai struktur DataFrame dapat dilihat menggunakan fungsi info()

`df.info()`

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2660 entries, 0 to 2659
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   periode_data      2660 non-null   int64  
 1   type_operasi      2660 non-null   object 
 2   area_operasi      2660 non-null   object 
 3   jumlah_bus        2450 non-null   float64
 4   jumlah_penumpang  2449 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 104.0+ KB


In [ ]:
list(df.columns)

['periode_data',
 'type_operasi',
 'area_operasi',
 'jumlah_bus',
 'jumlah_penumpang']

## Informasi Statistik
Informasi statistik untuk setiap kolom seperti nilai minimum, nilai maksimum, standar deviasi, rata-rata dan sebagainya, dapat ditampilkan dengan mengikuti perintah berikut

In [ ]:
df.describe()

periode_data   jumlah_bus  jumlah_penumpang
count    2660.000000  2450.000000       2449.000000
mean   202104.533835     7.716327        246.868926
std         2.453781    18.720744        825.569457
min    202101.000000     0.000000          0.000000
25%    202102.000000     1.000000          9.000000
50%    202105.000000     1.000000         13.000000
75%    202107.000000     1.000000         25.000000
max    202108.000000   125.000000       7268.000000

## Column selection, addition, deletion

Untuk melihat list column gunakan `df.columns`

In [ ]:
df.columns

Index(['type_operasi', 'daerah_operasi', 'area_operasi', 'jumlah_bus',
       'jumlah_penumpang'],
      dtype='object')

Kita dapat memilih kolom mana saja yang akan ditampilkan, yaitu dengan menyebutkan nama kolom yang akan ditampilkan.


Sebagai contoh kita hanya ingin menampilkan daerah_operasi

In [ ]:
df['tahun'] = 2021
df['bulan'] = 'Agustus'
df.head()

periode_data                type_operasi    area_operasi  jumlah_bus  \
0        202101         Puskesmas Cilincing  RS Wisma Atlet         1.0   
1        202101             Puskesmas Tebet  RS Wisma Atlet         1.0   
2        202101     Puskesmas Cempaka Putih  RS Wisma Atlet         1.0   
3        202101     Puskesmas Tanjung Priok  RS Wisma Atlet         1.0   
4        202101  Puskesmas Ciracas Tahap II  RS Wisma Atlet         1.0   

   jumlah_penumpang  tahun    bulan  
0               8.0   2021  Agustus  
1              24.0   2021  Agustus  
2              14.0   2021  Agustus  
3              10.0   2021  Agustus  
4               9.0   2021  Agustus

In [ ]:
df.loc[]

In [ ]:
df['daerah_operasi']

KeyError: 'daerah_operasi'

Contoh lain kita ingin menampilkan type_operasi, daerah_operasi, dan jumlah_penumpang

In [ ]:
df[['type_operasi', 'daerah_operasi', 'jumlah_penumpang']]

type_operasi daerah_operasi  jumlah_penumpang
0        ZONASI         ZONA 1             20358
1        ZONASI         ZONA 2             16302
2        ZONASI         ZONA 3             11416
3        ZONASI         ZONA 4             18655
4        ZONASI         ZONA 5             12332
5        ZONASI         ZONA 6              6407
6        ZONASI         ZONA 7             10153
7        ZONASI         ZONA 8               751
8        ZONASI         ZONA 9             11794
9        ZONASI        ZONA 10              6803
10       ZONASI        ZONA 11              4969
11      REGULER         RUTE 1             25549
12      REGULER         RUTE 2             18334
13      REGULER         RUTE 3             27055
14      REGULER         RUTE 4              1943
15      REGULER        RUTE 4A              2266
16      REGULER         RUTE 5             36009
17      REGULER         RUTE 6             18192
18      REGULER         RUTE 7             32202
19      REGULER         RUTE 8             17519
20      REGULER         RUTE 9              8607
21      REGULER        RUTE 10             14152
22      REGULER        RUTE 11             16593
23      REGULER        RUTE 12             30234
24      REGULER        RUTE 13              2049
25      REGULER        RUTE 14              1646
26      REGULER        RUTE 15             14341
27      REGULER        RUTE 16             11595
28      REGULER        RUTE 17             16694
29      REGULER        RUTE 18              4753
30      REGULER        RUTE 19              5344

**adding column**

untuk menambahkan column, sama seperti dictionary, cukup definisikan column baru nya

In [ ]:
df["column baru"] = "New column"

In [ ]:
df.head()

type_operasi daerah_operasi                                 area_operasi  \
0       ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
1       ZONASI         ZONA 2                ZONASI KP.MELAYU - RAWAMANGUN   
2       ZONASI         ZONA 3            ZONASI TERMINAL KALIDERES - KAMAL   
3       ZONASI         ZONA 4        ZONASI KALIDERES -SEMANAN-DURIKOSAMBI   
4       ZONASI         ZONA 5           ZONASI PULO GADUNG-MARDANI-PASEBAN   

   jumlah_bus  jumlah_penumpang column baru  
0         100             20358  New column  
1          84             16302  New column  
2          67             11416  New column  
3         102             18655  New column  
4          68             12332  New column

**deleting column**

untuk menghapus column, gunakan `df.drop`

In [ ]:
df = df.drop(columns=["column baru"])

In [ ]:
df.head()

type_operasi daerah_operasi                                 area_operasi  \
0       ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
1       ZONASI         ZONA 2                ZONASI KP.MELAYU - RAWAMANGUN   
2       ZONASI         ZONA 3            ZONASI TERMINAL KALIDERES - KAMAL   
3       ZONASI         ZONA 4        ZONASI KALIDERES -SEMANAN-DURIKOSAMBI   
4       ZONASI         ZONA 5           ZONASI PULO GADUNG-MARDANI-PASEBAN   

   jumlah_bus  jumlah_penumpang  
0         100             20358  
1          84             16302  
2          67             11416  
3         102             18655  
4          68             12332

## Data Indexing and Selection
Salah satu bagian penting yang digunakan dalam penyiapan data dan analisis data adalah filtering, yaitu pemilihan data dengan kriteria tertentu.

**Python loc() function**

*Example 1*

Bagi mereka yang terbiasa menggunakan SQL, ini adalah bagian dari pernyataan WHERE.

Misalnya, ingin menampilkan data untuk rute bus dengan jumlah bus >= 70

In [ ]:
df.head()

periode_data                type_operasi    area_operasi  jumlah_bus  \
0        202101         Puskesmas Cilincing  RS Wisma Atlet         1.0   
1        202101             Puskesmas Tebet  RS Wisma Atlet         1.0   
2        202101     Puskesmas Cempaka Putih  RS Wisma Atlet         1.0   
3        202101     Puskesmas Tanjung Priok  RS Wisma Atlet         1.0   
4        202101  Puskesmas Ciracas Tahap II  RS Wisma Atlet         1.0   

   jumlah_penumpang  tahun    bulan  
0               8.0   2021  Agustus  
1              24.0   2021  Agustus  
2              14.0   2021  Agustus  
3              10.0   2021  Agustus  
4               9.0   2021  Agustus

In [ ]:
df.loc[df.jumlah_penumpang > 20]

periode_data                                       type_operasi  \
1           202101                                    Puskesmas Tebet   
8           202101                          Puskesmas Ciracas Tahap I   
20          202101                          Puskesmas Ciracas Tahap I   
25          202101                            Puskesmas Tanjung Priok   
38          202101                            Puskesmas Cempaka Putih   
...            ...                                                ...   
2633        202108             PESERTA VAKSINASI KELILING BUS SEKOLAH   
2634        202108             PESERTA VAKSINASI KELILING BUS SEKOLAH   
2635        202108             PESERTA VAKSINASI KELILING BUS SEKOLAH   
2636        202108             PESERTA VAKSINASI KELILING BUS SEKOLAH   
2637        202108  PASIEN COVID19 YANG SUDAH SELESAI ISOLASI DARI...   

        area_operasi  jumlah_bus  jumlah_penumpang  tahun    bulan  
1     RS Wisma Atlet         1.0              24.0   2021  Agustus  
8     RS Wisma Atlet         1.0              22.0   2021  Agustus  
20    RS Wisma Atlet         1.0              22.0   2021  Agustus  
25    RS Wisma Atlet         1.0              28.0   2021  Agustus  
38    RS Wisma Atlet         1.0              21.0   2021  Agustus  
...              ...         ...               ...    ...      ...  
2633       KEMBANGAN         3.0              98.0   2021  Agustus  
2634        PALMERAH         3.0             559.0   2021  Agustus  
2635      TAMAN SARI         3.0             100.0   2021  Agustus  
2636         TAMBORA         3.0             433.0   2021  Agustus  
2637   JAKARTA UTARA         1.0              39.0   2021  Agustus  

[718 rows x 7 columns]

Misalnya, ingin menampilkan data untuk rute bus dengan jumlah bus >= 70, namun hanya column type_operasi dan daerah_operasi saja yang ditampilkan

In [ ]:
df.loc[df.jumlah_penumpang > 20 & (df.jumlah_bus > 2)]

periode_data                type_operasi  \
0           202101         Puskesmas Cilincing   
1           202101             Puskesmas Tebet   
2           202101     Puskesmas Cempaka Putih   
3           202101     Puskesmas Tanjung Priok   
4           202101  Puskesmas Ciracas Tahap II   
...            ...                         ...   
2655        202108                RUTE REGULER   
2656        202108                RUTE REGULER   
2657        202108                RUTE REGULER   
2658        202108                RUTE REGULER   
2659        202108                RUTE REGULER   

                                           area_operasi  jumlah_bus  \
0                                        RS Wisma Atlet         1.0   
1                                        RS Wisma Atlet         1.0   
2                                        RS Wisma Atlet         1.0   
3                                        RS Wisma Atlet         1.0   
4                                        RS Wisma Atlet         1.0   
...                                                 ...         ...   
2655  RUTE 13 (PULOGADUNG - PD.BAMBU - KALI MALANG -...         2.0   
2656                         RUTE 14 (BLOK M - PD.LABU)         3.0   
2657         RUTE 15 (TEBET - CIPINANG MUARA - PD.KOPI)         0.0   
2658          RUTE 16 (RUSUN MUARA BARU PLUIT - GROGOL)         0.0   
2659  RUTE 17 (RUSUN MUARA BARU PLUIT - BANDENGAN MU...         0.0   

      jumlah_penumpang  tahun    bulan  
0                  8.0   2021  Agustus  
1                 24.0   2021  Agustus  
2                 14.0   2021  Agustus  
3                 10.0   2021  Agustus  
4                  9.0   2021  Agustus  
...                ...    ...      ...  
2655               2.0   2021  Agustus  
2656               2.0   2021  Agustus  
2657               2.0   2021  Agustus  
2658               2.0   2021  Agustus  
2659               2.0   2021  Agustus  

[2361 rows x 7 columns]

In [ ]:
df.loc[df.jumlah_bus >= 70, ['type_operasi', 'daerah_operasi']]

type_operasi daerah_operasi
0        ZONASI         ZONA 1
1        ZONASI         ZONA 2
3        ZONASI         ZONA 4
11      REGULER         RUTE 1
12      REGULER         RUTE 2
13      REGULER         RUTE 3
15      REGULER        RUTE 4A
16      REGULER         RUTE 5
17      REGULER         RUTE 6
18      REGULER         RUTE 7
19      REGULER         RUTE 8
22      REGULER        RUTE 11
23      REGULER        RUTE 12
24      REGULER        RUTE 13
25      REGULER        RUTE 14

Penggabungkan beberapa kondisi dapat menggunakan operator logika `AND("&")` dan operator logika `OR("|")` untuk memilih baris dengan lebih dari satu kriteria.

Misalnya kita ingin menampilkan data dengan jumlah bus > 70 dan jumlah penumpang > 20000

In [ ]:
df.loc[(df.jumlah_bus >= 70) & (df.jumlah_penumpang > 20000)]

type_operasi daerah_operasi                                 area_operasi  \
0        ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
11      REGULER         RUTE 1           LAP.BANTENG - GALUR -P.KEMERDEKAAN   
13      REGULER         RUTE 3                      GANDARIA - H E K - TMII   
16      REGULER         RUTE 5                KAMPUNG MELAYU - TMII - CEGER   
18      REGULER         RUTE 7         PASAR MINGGU - RANCO - LT.AGUNG - UI   
23      REGULER        RUTE 12              TERMINAL KALIDERES - GAJAH MADA   

    jumlah_bus  jumlah_penumpang  
0          100             20358  
11          94             25549  
13          95             27055  
16         128             36009  
18         101             32202  
23         101             30234

Penggunaan operator logika `AND ("&")` di atas, akan mengambil data yang cocok dengan kedua kriteria tersebut. Jika Anda ingin mendapatkan data yang cocok hanya untuk salah satu kriteria, dapat menggunakan operator logika `OR("|")`

Fungsi `isin()` dapat digunakan untuk memfilter kolom jika nilainya ditentukan dalam bentuk list/daftar.

In [ ]:
# daerah_operasi = ['ZONA 1', 'ZONA 2', "ZONA 10", "ZONA 99", "RUTE 5"]

df.loc[
    (df.daerah_operasi.isin(['ZONA 1', 'ZONA 2', "ZONA 10", "ZONA 99", "RUTE 5"]))
    & (df.jumlah_penumpang > 20000)
  ]

type_operasi daerah_operasi                                 area_operasi  \
0        ZONASI         ZONA 1  ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO   
16      REGULER         RUTE 5                KAMPUNG MELAYU - TMII - CEGER   

    jumlah_bus  jumlah_penumpang  
0          100             20358  
16         128             36009

Untuk penyataan negasi atau NOT menggunakan tanda '~'

In [ ]:
df.loc[
    ~(df.daerah_operasi.isin(['RUTE 1', 'RUTE 4', 'RUTE 7', 'RUTE 10']))
    # & (df.jumlah_penumpang > 20000)
  ]

type_operasi daerah_operasi  \
0        ZONASI         ZONA 1   
1        ZONASI         ZONA 2   
2        ZONASI         ZONA 3   
3        ZONASI         ZONA 4   
4        ZONASI         ZONA 5   
5        ZONASI         ZONA 6   
6        ZONASI         ZONA 7   
7        ZONASI         ZONA 8   
8        ZONASI         ZONA 9   
9        ZONASI        ZONA 10   
10       ZONASI        ZONA 11   
12      REGULER         RUTE 2   
13      REGULER         RUTE 3   
15      REGULER        RUTE 4A   
16      REGULER         RUTE 5   
17      REGULER         RUTE 6   
19      REGULER         RUTE 8   
20      REGULER         RUTE 9   
22      REGULER        RUTE 11   
23      REGULER        RUTE 12   
24      REGULER        RUTE 13   
25      REGULER        RUTE 14   
26      REGULER        RUTE 15   
27      REGULER        RUTE 16   
28      REGULER        RUTE 17   
29      REGULER        RUTE 18   
30      REGULER        RUTE 19   

                                         area_operasi  jumlah_bus  \
0         ZONASI PONDOK GEDE - HALIM- CONDET - RANCHO         100   
1                       ZONASI KP.MELAYU - RAWAMANGUN          84   
2                   ZONASI TERMINAL KALIDERES - KAMAL          67   
3               ZONASI KALIDERES -SEMANAN-DURIKOSAMBI         102   
4                  ZONASI PULO GADUNG-MARDANI-PASEBAN          68   
5                   ZONASI CAWANG - PEJATEN - RAGUNAN          66   
6             ZONASI RAWAMANGUN - CIKINI - LP.BANTENG          68   
7   ZONASI LUBANG BUAYA - DUKU.5 - KP.RAMBUTAN - R...          67   
8                            ZONASI MARUNDA - ROROTAN          50   
9                          ZONASI MARUNDA - CILINCING          51   
10                      ZONASI - RUSUN KAPUK - CIDENG          34   
12                      PLUMPANG - SUNTER - KEMAYORAN          80   
13                            GANDARIA - H E K - TMII          95   
15                          PULO GADUNG - PONDOK KOPI          79   
16                      KAMPUNG MELAYU - TMII - CEGER         128   
17      PS.MINGGU - MAMPANG PRAPATAN - KEBAYORAN PTIK          80   
19                  PS. MINGGU - PANCORAN - MANGGARAI          82   
20                CILINCING - PLUMPANG -P.KEMERDEKAAN          49   
22                                   BLOK.M - CILEDUK          79   
23                    TERMINAL KALIDERES - GAJAH MADA         101   
24                PULO GADUNG -  PONDOK BAMBU -CAWANG         102   
25                              BLOK. M - PONDOK LABU          85   
26                                TEBET - PONDOK KOPI          67   
27                          RUSUN MUARA BARU - GROGOL          34   
28                            MUARA BARU- MUARA ANGKE          51   
29                 TEBET - MAMPANG PRAPATAN - RAGUNAN          34   
30            MANGGARAI - MAMPANG PRAPATAN- PS MINGGU          34   

    jumlah_penumpang  
0              20358  
1              16302  
2              11416  
3              18655  
4              12332  
5               6407  
6              10153  
7                751  
8              11794  
9               6803  
10              4969  
12             18334  
13             27055  
15              2266  
16             36009  
17             18192  
19             17519  
20              8607  
22             16593  
23             30234  
24              2049  
25              1646  
26             14341  
27             11595  
28             16694  
29              4753  
30              5344

**Memfilter data menggunakan index**

Kita dapat menampilkan data berdasarkan index nya dengan menggunakan `loc` dan `iloc`

In [ ]:
df.loc[10:15]

type_operasi daerah_operasi  \
10       ZONASI        ZONA 11   
11      REGULER         RUTE 1   
12      REGULER         RUTE 2   
13      REGULER         RUTE 3   
14      REGULER         RUTE 4   
15      REGULER        RUTE 4A   

                                       area_operasi  jumlah_bus  \
10                    ZONASI - RUSUN KAPUK - CIDENG          34   
11               LAP.BANTENG - GALUR -P.KEMERDEKAAN          94   
12                    PLUMPANG - SUNTER - KEMAYORAN          80   
13                          GANDARIA - H E K - TMII          95   
14  PERINTIS KEMERDEKAAN - PULO GADUNG- PONDOK KOPI          63   
15                        PULO GADUNG - PONDOK KOPI          79   

    jumlah_penumpang  
10              4969  
11             25549  
12             18334  
13             27055  
14              1943  
15              2266

In [ ]:
df.iloc[10:15]

type_operasi daerah_operasi  \
10       ZONASI        ZONA 11   
11      REGULER         RUTE 1   
12      REGULER         RUTE 2   
13      REGULER         RUTE 3   
14      REGULER         RUTE 4   

                                       area_operasi  jumlah_bus  \
10                    ZONASI - RUSUN KAPUK - CIDENG          34   
11               LAP.BANTENG - GALUR -P.KEMERDEKAAN          94   
12                    PLUMPANG - SUNTER - KEMAYORAN          80   
13                          GANDARIA - H E K - TMII          95   
14  PERINTIS KEMERDEKAAN - PULO GADUNG- PONDOK KOPI          63   

    jumlah_penumpang  
10              4969  
11             25549  
12             18334  
13             27055  
14              1943

## Handling missing data

Perbedaan antara data yang ditemukan di banyak tutorial dan data di dunia nyata adalah bahwa data di dunia nyata jarang sekali bersih dan homogen. Lebih rumit lagi, sumber data yang berbeda mungkin menunjukkan data yang hilang dengan cara yang berbeda.

terdapat beberapa function yang dipakai untuk menghandle null values dalam Pandas data structures.


```
isnull(): Generate a boolean mask indicating missing values
notnull(): Opposite of isnull()
dropna(): Return a filtered version of the data
fillna(): Return a copy of the data with missing values filled or imputed
```



### Detecting Null

Untuk mengecek data yang null atau tidak, gunakan `isnull() and notnull()`

In [ ]:
data_penjualan = {
  "product": ["product A", "product B", "product C", "product X"],
  "hasil_penjualan": [500000, None, 125000, np.nan]
}
df = pd.DataFrame(data_penjualan)

print(df)

     product  hasil_penjualan
0  product A         500000.0
1  product B              NaN
2  product C         125000.0
3  product X              NaN


In [ ]:
df.isnull()

product  hasil_penjualan
0    False            False
1    False             True
2    False            False
3    False             True

In [ ]:
df.notnull()

product  hasil_penjualan
0     True             True
1     True            False
2     True             True
3     True            False

### Dropping null values

terdapat function `dropna()` untuk menghapus null data dan fillna() untuk mengisi null value

In [ ]:
df.dropna()

product  hasil_penjualan
0  product A         500000.0
2  product C         125000.0

In [ ]:
# Sometimes rather than dropping NA values,
# you'd rather replace them with a valid value.
# This value might be a single number like zero,
# or it might be some sort of imputation
# or interpolation from the good values.

df.fillna(1000000)

product  hasil_penjualan
0  product A         500000.0
1  product B        1000000.0
2  product C         125000.0
3  product X        1000000.0

In [1]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


In [2]:
import numpy as np

array1 = np.array([1, 2, 3, 4])
array2 = np.array([2, 3, 4, 5])
result = np.sum(array2) - np.sum(array1)

print(result)

4


In [3]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])
result = np.sum(array, axis=1)

print(result)

[ 6 15]
